"""
This package provides a simple and clean Django web ui for querying Mongo
collections. While it was designed with the collections generated by
VaspToDbTaskDrone in mind, it can be used with any Mongo collection with the
appropriate settings.
"""
