name: Testing

on: [push, pull_request]

jobs:
  build:

    strategy:
      max-parallel: 20
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
        mongodb-version: [4.4]

    runs-on: ${{ matrix.os }}

    env:
      PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
      MPLBACKEND: "Agg"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.4.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --quiet -r requirements.txt -r requirements-ci.txt
        pip install -e .
    - name: pytest
      run: |
        pytest --cov=pymatgen.db --durations=30 pymatgen
