name: Test

on: [push, pull_request]

jobs:
  build:

    strategy:
      max-parallel: 20
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
        mongodb-version: [4.4]

    runs-on: ${{ matrix.os }}

    env:
      PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
      MPLBACKEND: "Agg"

    steps:
      - uses: actions/checkout@v4
      - name: Install uv.
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.4.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install dependencies
        run: uv sync
      - name: pytest
        run: uv run pytest --cov=pymatgen.db --cov-report=xml pymatgen --color=yes
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v5
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
